before_script:
  - apt-get update && apt-get install -y mysql-client
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go mod download

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    MYSQL_DATABASE: "coke_test"
    MYSQL_ROOT_PASSWORD: "root"
    TEST_DATABASE_URL: "mysql://root:root@(mysql:3306)/coke_test?parseTime=true&multiStatements=true&readTimeout=1s"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-15
  image: golang:1.15

test:
  # Change to "<<: *use-golang-latest" to use the latest Go version
  <<: *use-golang-1-15
  <<: *test-vars
  stage: test
  services:
    - mysql:5
  script:
    - buffalo test
